services:
  server:
    build:
      context: ./server
      target: Prod
    ports:
      - "3001:3001"
    volumes:
      - ./server/.env:/app/.env

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
